// <auto-generated />
namespace WinFormQuanLyNhaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Edit_Timestamp_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit_Timestamp_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "202112130348433_Edit_Timestamp_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
